name: craft
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pytorch=1.1.0
  - torchvision=0.3.0
  - click=6.7
  - matplotlib=3.1.1
  - numpy=1.17.0
  - opencv
  - scipy=1.3.0
  - tqdm=4.32.1
  - networkx
  - shapely
